### PR TITLE
Adds an implementation-notes section to the configuration file

### PR DESCRIPTION
**Pull request by gregjan**
Adds a map of implementation notes, keyed by the specification section reference (3.1.1-A, for instance), to the configuration YAML file. Each implementation within the file can detail in plain text their support for certain features or explanations for why a certain test might fail to complete.

### CODE REVIEW

**Comment by gregjan** [comment]
Unfortunately I don't understand the CI failure above well enough to address it. Can someone unpack that for me?

**Comment by bbpennel** [comment]
It's not related to your changes. Travis changed their default box distribution moderately recently from, I believe from `trusty` to `xenial`. If you expand the "Build system information" section it lists this. The new default doesn't include openjdk8 anymore. This can be addressed by updating .travis.yml to specify the distribution with `dist: trusty`, or we could probably up the jdk version to 9 or higher.

**Comment by awoods** [comment]
Hopefully https://github.com/fcrepo/Fedora-API-Test-Suite/pull/328 does the trick.

**Comment by awoods** [comment]
@gregjan : now that https://github.com/fcrepo/Fedora-API-Test-Suite/pull/328 has been merged, can you rebase this PR on `master`?

**Comment by gregjan** [comment]
Yes, I'll do that shortly.

**Pull request merged**
